openapi: 3.0.3
info:
  title: Weather Mood API
  version: 1.0.0
  description: REST API for access to recorded Moods
paths:
  /moods/:
    get:
      operationId: moods_list
      description: Gets all the recorded mood log entries.
      parameters:
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      tags:
      - moods
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMoodLogList'
          description: ''
    post:
      operationId: moods_create
      description: Create a new mood log entry.
      tags:
      - moods
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mood'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Mood'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Mood'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoodLog'
          description: ''
  /moods/{id}/:
    get:
      operationId: moods_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mood log.
        required: true
      tags:
      - moods
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoodLog'
          description: ''
    put:
      operationId: moods_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mood log.
        required: true
      tags:
      - moods
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoodLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MoodLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/MoodLog'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoodLog'
          description: ''
    patch:
      operationId: moods_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mood log.
        required: true
      tags:
      - moods
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedMoodLog'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedMoodLog'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedMoodLog'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoodLog'
          description: ''
    delete:
      operationId: moods_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this mood log.
        required: true
      tags:
      - moods
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - ckb
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - ug
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
components:
  schemas:
    Mood:
      type: object
      properties:
        mood:
          type: number
          format: double
          description: Mood between 1 and 10
      required:
      - mood
    MoodLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
          description: User that created log entry
        mood:
          type: number
          format: double
          description: Mood between 1 and 10
        time:
          type: string
          format: date-time
          readOnly: true
          description: Log time for the entry
      required:
      - id
      - mood
      - time
      - user
    PaginatedMoodLogList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/MoodLog'
    PatchedMoodLog:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: integer
          readOnly: true
          description: User that created log entry
        mood:
          type: number
          format: double
          description: Mood between 1 and 10
        time:
          type: string
          format: date-time
          readOnly: true
          description: Log time for the entry
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
